# Jekyll Configuration
title: "B4ltasar's Website"
description: "Personal website"
url: "https://b4ltasar.github.io"
baseurl: "/website"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - _archive/
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - mailchimp-api.js

# Collections (hvis du får brug for det senere)
# collections:
#   posts:
#     output: true

# Default layout
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
