name: Deploy NEARWEEK to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build site
        run: |
          echo "Building NEARWEEK site..."
          
          # Create CNAME file for custom domain
          echo "nearweek.com" > CNAME
          
          # Generate sitemap
          cat > sitemap.xml << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <url>
              <loc>https://nearweek.com/</loc>
              <lastmod>$(date -u +%Y-%m-%dT%H:%M:%S+00:00)</lastmod>
              <changefreq>daily</changefreq>
              <priority>1.0</priority>
            </url>
          </urlset>
          EOF
          
          # Generate robots.txt
          cat > robots.txt << EOF
          User-agent: *
          Allow: /
          
          Sitemap: https://nearweek.com/sitemap.xml
          EOF
          
          echo "Build complete!"
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
      - name: Notify deployment success
        run: |
          echo "ðŸš€ NEARWEEK successfully deployed!"
          echo "ðŸŒ Live at: https://nearweek.com"
