[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/newsletter"
  to = "/newsletter.html"
  status = 200

[[redirects]]
  from = "/api/newsletter"
  to = "/.netlify/functions/latest-newsletter"
  status = 200

[context.production.environment]
  MAILCHIMP_API_KEY = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"